---
defaults: &defaults
  apdex_t: 0.5
  ssl: false
  monitor_mode: true
  license_key: foobarbaz 
  developer_mode: false
  app_name: RatPack 
  capture_params: true 
  log_level: info
  browser_monitoring:
    auto_instrument: true

development:
  <<: *defaults
  monitor_mode: false
  developer_mode: true
  log_level: debug
test:
  <<: *defaults
  monitor_mode: false
staging:
  <<: *defaults
  monitor_mode: true
production:
  <<: *defaults
  monitor_mode: true

